server:
  #  监听端口，0.0.0.0 允许任意主机连接
  listen_host: "0.0.0.0"  # server 端监听的主机地址
  listen_port: 2222 # 命令连接的监听的端口

PORT:
  data_connection_port: 2221 # PORT 模式下的数据端口

PASV:  # PASV 模式，指定该模式下可以使用的端口范围
  port_low: 22222 # 数据连接所用的端口下限
  port_high: 55555  # 数据连接所用的端口上限
  # PASV 模式中强制使用的 IP 地址，在 NAT 网关后的主机可能不能自动解析到公网 IP
  #   或者在网关采用动态 IP 的情况下有用
  force_passive_ip: "" # 若使用程序自动解析的 ip 地址，则填为空字符串 ""

SERVICE:
  max_upload_speed: 409600  # 上传速度, 400k Bytes/s
  max_download_speed: 409600  # 下载速度, 400k Bytes/s
